networks:
  poc-nestjs-serverless:
    driver: bridge

services:
  aws-lambda-layer:
    image: aws-lambda-layer:latest
    environment:
      - AWS_REGION
    build:
      context: .
      dockerfile: ./deployment/aws-lambda/layers/Dockerfile

  database-auth:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_AUTH_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_AUTH_PASSWORD}
      POSTGRES_DB: ${DATABASE_AUTH_DBNAME}
    networks:
      - poc-nestjs-serverless
    ports:
      - ${DATABASE_AUTH_PORT}:5432
    volumes:
      - ./deployment/database/authentication:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7.4.1
    networks:
      - poc-nestjs-serverless
    restart: always
    ports:
      - ${REDIS_PORT}:6379

  redis-ui:
    image: patrikx3/p3x-redis-ui:2024.10.106
    networks:
      - poc-nestjs-serverless
    ports:
      - 7843:7843
    volumes:
      - ./deployment/redis-ui:/settings

  openapi-merge:
    image: openapi-merge:latest
    build:
      context: .
      dockerfile: ./deployment/openapi/Dockerfile
    volumes:
      - ./deployment/openapi/json-merger.js:/home/node/app/json-merger.js:ro
      - ./apps/login/docs/openapi/openapi-docs.json:/openapi/login/openapi-docs.json:ro
      - ./apps/logout/docs/openapi/openapi-docs.json:/openapi/logout/openapi-docs.json:ro
      - ./docs/openapi/openapi-docs.json:/openapi/openapi-docs.json
    command: node json-merger.js

  openapi:
    image: nginx:1.27.2-alpine3.20
    ports:
      - 8081:80
    volumes:
      - ./docs/openapi:/usr/share/nginx/html:ro
