networks:
  poc-nestjs-serverless:
    driver: bridge

services:
  aws-node-modules:
    image: aws-node-modules:latest
    build:
      context: .
      dockerfile: ./deployment/aws_lambda/layers/Dockerfile

  database-auth:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_AUTH_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_AUTH_PASSWORD}
      POSTGRES_DB: ${DATABASE_AUTH_DBNAME}
    networks:
      - poc-nestjs-serverless
    ports:
      - ${DATABASE_AUTH_PORT}:5432
    volumes:
      - ./deployment/database/authentication:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7.4.1
    networks:
      - poc-nestjs-serverless
    restart: always
    ports:
      - ${REDIS_PORT}:6379

  redis-ui:
    image: patrikx3/p3x-redis-ui:2024.10.106
    networks:
      - poc-nestjs-serverless
    ports:
      - 7843:7843
    volumes:
      - ./deployment/redis-ui:/settings
