networks:
  poc-nestjs-serverless:
    driver: bridge

services:
  database-auth:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_AUTH_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_AUTH_PASSWORD}
      POSTGRES_DB: ${DATABASE_AUTH_DBNAME}
    networks:
      - poc-nestjs-serverless
    ports:
      - ${DATABASE_AUTH_PORT}:5432
    volumes:
      - ./deployment/database/authentication:/docker-entrypoint-initdb.d:ro
