# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: serveless1
service: poc-nestjs-serverless

provider:
  name: aws
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-0bb02e3f7ef39fdf5
    subnetIds:
      - subnet-0c19620347ff05c33
  profile: aws-serverless
  stage: ${opt:stage, 'dev'}
  runtime: nodejs20.x
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
  timeout: 2 # in seconds

plugins:
  - serverless-offline

package:
  individually: true

# The name of your layer in the CloudFormation template will be your layer name TitleCased (without spaces) and have LambdaLayer appended to the end
# For a layer named "Test", use "!Ref TestLambdaLayer"
layers:
  node:
    description: A layer with node_modules for production environment and database certificates
    path: aws_node_layer
    package:
      # see project /docs/markdown/how-to-deploy.md to details as how to generate the aws-lambda-layer.zip file
      artifact: aws-lambda-layer/aws-lambda-layer.zip

functions:
  login:
    environment: ${file(.env.json)}
    package:
      include:
        - dist/apps/login/lambda.js
      exclude:
        - ./**
    handler: dist/apps/login/lambda.handler
    layers:
      - !Ref NodeLambdaLayer
    events:
      - http:
          method: POST
          path: /login

  logout:
    environment: ${file(.env.json)}
    package:
      include:
        - dist/apps/logout/lambda.js
      exclude:
        - ./**
    handler: dist/apps/logout/lambda.handler
    layers:
      - !Ref NodeLambdaLayer
    events:
      - http:
          method: POST
          path: /logout
